[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_smart_contract = "3sybqPuS4jNM9txKMe15F72UR6gys4eoJoHHHrigTJ8Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mruserbox/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
